repos:
  - repo: "https://github.com/antonbabenko/pre-commit-terraform"
    rev: v1.72.1
    hooks:
      - id: terraform_fmt
        args:
          - "--args=-recursive"
      - id: terraform_validate
      - id: terraform_docs
        args:
          - "--hook-config=--add-to-existing-file=false"
          - "--hook-config=--create-file-if-not-exist=true"
